### ISSUE TITLE
need api key?

### ISSUE THREAD

**Issue by wukong7788** [JerBouma/FundamentalAnalysis#10]
when I first use it, code as below:
```
import FundamentalAnalysis as fa

    ticker = "AAPL"
    # Show the available companies
    companies = fa.available_companies()
```

erros:
`{"Error Message" : "Invalid API KEY. Please retry or visit our documentation to create one FREE https://financialmodelingprep.com/developer/docs"}
Traceback (most recent call last):
  File "C:/Users/ron/Documents/us-stocks/spider.py", line 240, in <module>
    companies = fa.available_companies()
  File "C:\Users\ron\anaconda3\envs\py37\lib\site-packages\FundamentalAnalysis\details.py", line 23, in available_companies
    data_json = json.loads(data)['symbolsList']
KeyError: 'symbolsList'
`
SO, I need a API key? and where I can set?

**Comment by JerBouma** [comment]
This is a new change to the API. I am aware of it and will update the package soon.

**Comment by JerBouma** [comment]
With release 0.2.2, this issue is now fixed. Please update to the latest release.
