### ISSUE TITLE
earnings_calendar doesn't work

### ISSUE THREAD

**Issue by gabjew90** [JerBouma/FundamentalAnalysis#13]
Hi, how do I access earnings_calendar? 

AttributeError: module 'FundamentalAnalysis' has no attribute 'earnings_calendar'

**Comment by JerBouma** [comment]
Seems I forgot to add 'earnings_calendar' to the init file. Quick fix would be to add `from .details import earnings_calendar` to the __init__.py file. I will update the packages shortly.

**Comment by JerBouma** [comment]
Fixed, please update to version 0.2.5.
