### ISSUE TITLE
pip library broken

### ISSUE THREAD

**Issue by austenmyers** [JerBouma/FundamentalAnalysis#15]
Pip library seems to be broken, receiving this error:
ERROR: Could not find a version that satisfies the requirement FundamentalAnalysis (from versions: none)
ERROR: No matching distribution found for FundamentalAnalysis

**Comment by JerBouma** [comment]
![image](https://user-images.githubusercontent.com/46355364/116540492-827d5e80-a8ea-11eb-9b86-0a83184831e4.png)

Seems to be working fine. Check whether you perhaps made a spelling error?
