### ISSUE TITLE
Quarterly reports

### ISSUE THREAD

**Issue by Kander-5** [JerBouma/FundamentalAnalysis#16]
Looks like the quarterly reports may have recently broken. Attempted to pull income and cash flow on a quarterly basis, and was returned a "HTTP Error 403:"

Appears to be new as I was able to pull quarterly financials previously without issue. Maybe an update to the "Period" field?

**Comment by JerBouma** [comment]
Will look into this soon.

**Comment by JerBouma** [comment]
Everything seems to be running just fine if I run the code in the Example section of the README.md file.

Could you get to me with answers to the following:

- Are you on the most recent version of the package (0.2.7)?
- What kind of subscription do you have? Check whether you can actually collect data from that ticker based on your subscription: [https://financialmodelingprep.com/developer/docs/pricing/](https://financialmodelingprep.com/developer/docs/pricing/)
- Could you provide me with your code so I can check whether I receive the same error?

**Comment by carloscarrasco** [comment]
Thank you. I have the same problem with the "quarter" data. The "annual" is working fine but the "quarter" isn't.

**Comment by JerBouma** [comment]
Unfortunately, the data source (FinancialModellingPrep) decided to set the quarter datapoints to a Premium subscription. Therefore, you are not able to collect the data.

See for example: 
- [Annual (working)](https://financialmodelingprep.com/api/v3/income-statement/TSLA?period=annual&apikey=a015eaace08a8d46cfd49c849258a2bd)
- [Quarter (not working)(https://financialmodelingprep.com/api/v3/income-statement/TSLA?period=quarter&apikey=a015eaace08a8d46cfd49c849258a2bd)

This URL is the same as the request URL I make within this package. Therefore, the only solution is to upgrade your plan. I will be adding this error message in the code for other users as well.

**Comment by JerBouma** [comment]
Please update to version 0.2.8
