### ISSUE TITLE
Is possible to get the Intrinsic Value ? 

### ISSUE THREAD

**Issue by thomas2004ch** [JerBouma/FundamentalAnalysis#18]
Hi,

I try your wonderful package. I can get the discount cash flow of a stock/ticker. I see you use the financialmodelingprep.com to get the discount cash flow. But by financialmodelingprep.com there is Intrinsic Value. I wonder if one can get this via your package?

Regards

Thomas

**Comment by JerBouma** [comment]
Yes you can. Please check [here](https://github.com/JerBouma/FundamentalAnalysis#functions).
