### ISSUE TITLE
fa.stock_data Not Retrieving Data

### ISSUE THREAD

**Issue by ahmedalkadhi** [JerBouma/FundamentalAnalysis#20]
**Describe the bug**
Unable to use fa.stock_data

**To Reproduce**
Call function directly, unable to retrieve data.

**Expected behavior**
List of stocks with Start, Close, Etc

**Screenshots**

**Desktop (please complete the following information):**
Error:

JSONDecodeError                           Traceback (most recent call last)
<ipython-input-3-3e8b70ab194d> in <module>
----> 1 GSPC = fa.stock_data('AAPL', start = date_start, end = end_date )['close']

~/opt/anaconda3/lib/python3.8/site-packages/FundamentalAnalysis/stock_data.py in stock_data(ticker, period, interval, start, end)
     51     try:
     52         data = requests.get(url=url, params=parameters)
---> 53         data_json = data.json()['chart']['result'][0]
     54     except TypeError:
     55         raise TypeError("No data available. Please check if you have a valid period and/or interval. \n"

~/opt/anaconda3/lib/python3.8/site-packages/requests/models.py in json(self, **kwargs)
    896                     # used.
    897                     pass
--> 898         return complexjson.loads(self.text, **kwargs)
    899 
    900     @property

~/opt/anaconda3/lib/python3.8/json/__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    355             parse_int is None and parse_float is None and
    356             parse_constant is None and object_pairs_hook is None and not kw):
--> 357         return _default_decoder.decode(s)
    358     if cls is None:
    359         cls = JSONDecoder

~/opt/anaconda3/lib/python3.8/json/decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

~/opt/anaconda3/lib/python3.8/json/decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JerBouma** [comment]
Are you running on the latest version of the package? (which is 0.2.11)

When I run your code as follows: `GSPC = fa.stock_data('AAPL',)['close']`

Everything works just fine. Could it be that the start and end date simply has no data?

![image](https://user-images.githubusercontent.com/46355364/134945732-3447c68e-ec85-4da7-ac55-711c1986e5a5.png)

With dates filled in:
![image](https://user-images.githubusercontent.com/46355364/134946071-81e3b3d0-69fc-46e1-96ba-62b9eb8c3de8.png)

**Comment by ahmedalkadhi** [comment]
That is it ,,,

Thank You..

*Ahmed Alkadhi*

Email: ***@***.***
