### ISSUE TITLE
Can I use your package in Jupyter notebook?

### ISSUE THREAD

**Issue by nsarpangala** [JerBouma/FundamentalAnalysis#23]
![jupyter](https://user-images.githubusercontent.com/34322933/146628548-a681c894-c553-4c54-913e-e1b1d9e2800e.png)

Hi,

I installed FunamentalAnalysis within a conda environment. I can run it in a python script but I cannot use it in Jupyter notebook. Can you please guide if it is possible to use here? Please see the image for reference.

Thanks,
Niranjan

**Comment by JerBouma** [comment]
Perhaps restart Jupyter Notebook? It seems to work perfectly fine from my side:
![image](https://user-images.githubusercontent.com/46355364/146739285-ba1c9b27-a8f2-4fd4-8bc0-de213cef9d58.png)

**Comment by nsarpangala** [comment]
Alright, thank you @JerBouma. May be some error on my end. I will restart jupyter lab and try.
