### ISSUE TITLE
New Stock_Financial_Scores Feature?

### ISSUE THREAD

**Issue by blue-wild-angel** [JerBouma/FundamentalAnalysis#28]
Thank you for building the wonderful library.

I was wondering if you are going to add new features from FMP like the Stock-Financial-Scores 
(https://site.financialmodelingprep.com/developer/docs/#Stock-Financial-scores)

Thanks have a great day.

**Comment by JerBouma** [comment]
Currently I have no time to extend the library but feel free to create a PR for this yourself! :)

**Comment by blue-wild-angel** [comment]
Ok, thank you for your reply! have a wonderful day.
