### ISSUE TITLE
Calendar years instead of "year ended"

### ISSUE THREAD

**Issue by van-alfen** [JerBouma/FundamentalAnalysis#29]
The column names in the annual financial statements (the years) are occasionally off. For example, ticker DPZ filed their 10K for fiscal year 2020 on Jan 3, 2021 ([see here](https://www.sec.gov/ix?doc=/Archives/edgar/data/0001286681/000119312521055734/d326373d10k.htm); their fiscal year end is the Sunday closest to Dec 31). This results in 2020 data being reported as 2021. Same thing for the following year.

In `financial_statements.py`, `date = value['date'][:4]` could be replaced with `date = value['calendarYear']` in all three functions, and this would solve the issue. In this case I would also recommend not deleting date — `del value['date']` — since the user might also be interested in the fiscal year end date.

Lastly, and maybe this should be a separate issue, it seems unintuitive to have the year columns represented as a string instead of an integer. Wrapping the suggestion above in `int()` is an easy fix.

Figured I would mention these here in case I am missing something, but I'm happy to create a pull request if there are no objections.

**Comment by JerBouma** [comment]
Hi @van-alfen, unfortunately I have no time to work on this myself so feel free to PR! It makes sense what you are saying, I believe at the time I created the package there was no `calendarYear` value.
