### ISSUE TITLE
the calculation of quarterly evToSales

### ISSUE THREAD

**Issue by DrSarahZou** [JerBouma/FundamentalAnalysis#31]
Hello, I found a mistake in the formula of quarterly evToSales. It seems that you directly use EV/quarterly revenue, which makes the ratio about 4 times larger because the denominator should be an annual term. Usually we use LTM (last twelve months) revenue.

**Comment by JerBouma** [comment]
Hi! Please report this to the guys over at https://site.financialmodelingprep.com/. I am just the guy who made the connector, I have no access to any of the formulas :)
