### ISSUE TITLE
stock_data() doesn't compute the total returns

### ISSUE THREAD

**Issue by antonio-catalano** [JerBouma/FundamentalAnalysis#4]
In order to get the total returns of a stock we need the _adjusted close price_ of yahoo, but **stock_data()** calculates returns with the simple _close_ price.

**Comment by JerBouma** [comment]
On like 62 (and on) the following code (with small iterations) is displayed:

`stockdata['Close', s] = pdr.DataReader(s, 'yahoo', begin_time, end_time)['Close']`

You can change the stock_data.py file and replace `['Close']` with `['Adj Close'] `. This would then retrieve the Adjusted Close data. Feel free to create a parameter to the function and open a Pull requests.

**Comment by JerBouma** [comment]
Fully updated the package. Please update your version to use it.
