### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by tommifi** [JerBouma/FundamentalAnalysis#5]
Running the exemple on readme.md file I receive following error:

\lib\site-packages\FundamentalAnalysis\balance_sheet.py", line 55, in balance_sheet
    data = pd.read_html(lxml.etree.tostring(table[0], method='html'))[0].set_index(0).transpose()
IndexError: list index out of range

**Comment by JerBouma** [comment]
Duplicate of #1

Unfortunately this function broke down due to an overhaul of the Yahoo Fundamentals page.
