### ISSUE TITLE
Error encountered when runs

### ISSUE THREAD

**Issue by SnowyThinker** [JerBouma/FundamentalAnalysis#6]
![image](https://user-images.githubusercontent.com/4386778/74890323-ad068a00-53be-11ea-868b-84df9b6edca8.png)

**Comment by JerBouma** [comment]
Hi Snowy, I think the package reached the point of being fully unusable. Please have a look at [yFinance](https://github.com/ranaroussi/yfinance) which is still maintained well.

**Comment by JerBouma** [comment]
Fully updated the package. Please update your version to use it.
