### ISSUE TITLE
Incorrect financial statements

### ISSUE THREAD

**Issue by gabjew90** [JerBouma/FundamentalAnalysis#7]
![image](https://user-images.githubusercontent.com/64626637/81132567-b86c4a80-8f03-11ea-96fd-d561d501fb29.png)

Negative revenue and incorrect numbers like EPS, Rev, etc.

**Comment by JerBouma** [comment]
Thank you for the feedback, this seems to be a specific case. The data of 2020 Q1 and 2019 Q4 is incorrect. However, looking at a different company, for example Tesla, I see correct numbers:

![image](https://user-images.githubusercontent.com/46355364/81145642-f2c2ff80-8f76-11ea-82fd-760ecbb1ff6b.png)

Therefore, I am going to revisit this issue next week to see if this still is a problem. These figures could be updated by then.

**Comment by JerBouma** [comment]
Issue fixed with latest versions (0.2.3). Please update to obtain the most up-to-date data.
![image](https://user-images.githubusercontent.com/46355364/82835752-45803f00-9ec5-11ea-8bf1-352381e03454.png)
