### ISSUE TITLE
Line 22 in Available Companies Code Error?

### ISSUE THREAD

**Issue by exodusraven** [JerBouma/FundamentalAnalysis#9]
**Describe the bug**
Hello, Im afraid that im new to programming but i had this code running perfectly fine but for whatever reason it seems to stop working properly few days later. Im not to sure but it has something to do with line 22 in available companies file. 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/61141214/82637441-a0f6b800-9bb9-11ea-8787-cda3a55a59fb.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JerBouma** [comment]
I aware of this issue and will fix it soon!

**Comment by exodusraven** [comment]
Wow, your fast to respond and thank you for looking into this issue, Have a fine evening. Good sir.

**Comment by JerBouma** [comment]
Updated the package, please update to version 0.2.2 and obtain an API key (see README).
